# Generated by Django 5.0.4 on 2024-04-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=13, unique=True, verbose_name='Телефон'),
        ),
    ]
